export const products = [
  {
    id: 1,
    name: "ELEGANT MOUTHSPRAY",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolo ",
    image: "/image/elegant/640hong1_.jpg",
    slideImage: [
      "/image/elegant/640hong1_.jpg",
      "/image/elegant/640sanse.jpg",
      "/image/elegant/640shuna.jpg",
      "/image/elegant/hong.jpg",
      "/image/elegant/kafei.jpg",
      "/image/elegant/lan.jpg",
    ],
  },
  {
    id: 2,
    name: "HANDHELD WATERFLOSSER",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor nisi",
    image: "/image/handheld/2.png",
    slideImage: [
      "/image/handheld/2.png",
      "/image/handheld/4.937.png",
      "/image/handheld/4.938_.png",
      "/image/handheld/4.png",
      "/image/handheld/5.png",
      "/image/handheld/7.jpg",
      "/image/handheld/5034.jpg",
      "/image/handheld/5035.jpg",
    ],
  },
  {
    id: 3,
    name: "HOME TEETH WHITENING KIT",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor ni",
    image: "/image/homewhite/564fjps2011.jpg",
    slideImage: [
      "/image/homewhite/564fjps2011.jpg",
      "/image/homewhite/564fjps2012.jpg",
      "/image/homewhite/564fjps2013.jpg",
      "/image/homewhite/564fjps2014.jpg",
      "/image/homewhite/564fjps2015.jpg",
      "/image/homewhite/564fjps2016.jpg",
      "/image/homewhite/564fjps2017_.jpg",
      "/image/homewhite/564fjps2018_2.jpg",
      "/image/homewhite/564fjps2019_.jpg",
      "/image/homewhite/2012.jpg",
      "/image/homewhite/2013.jpg",
      "/image/homewhite/2014.jpg",
      "/image/homewhite/2018.jpg",
      "/image/homewhite/4354fgj.jpg",
      "/image/homewhite/za.jpg",
    ],
  },

  {
    id: 4,
    name: "V34 TEETH COLOUR CORRECTOR",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor ",
    image: "/image/v34.jpeg",
    slideImage: ["/image/v34.jpeg"],
  },

  {
    id: 5,
    name: "LED LIGHT TEETH WHITENING KIT",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolo",
    image: "/image/ledlight/2 (1).jpg",
    slideImage: [
      "/image/ledlight/2 (1).jpg",
      "/image/ledlight/105za(3).jpg",
      "/image/ledlight/2142fg.jpg",
      "/image/ledlight/220721-3.jpg",
      "/image/ledlight/121212124.jpg",
      "/image/ledlight/detail page1.jpg",
      "/image/ledlight/detail page2.jpg",
    ],
  },
  {
    id: 6,
    name: "CLASSY MOUTHSPRAY",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor n",
    image: "/image/mouthspray/kkkss1_222.jpg",
    slideImage: [
      "/image/mouthspray/kkkss1_222.jpg",
      "/image/mouthspray/kkkss3_222.jpg",
      "/image/mouthspray/kkkss4_222.jpg",
      "/image/mouthspray/detail page.jpg",
      "/image/mouthspray/kkkss5_222.jpg",
      "/image/mouthspray/kkkss6_222.jpg",
      "/image/mouthspray/kkkss7_222.jpg",
      "/image/mouthspray/kkkss8_.jpg",
    ],
  },
  {
    id: 7,
    name: "ULTRASONIC TEETH SCALER",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor",
    image: "/image/scalar/DSCF5753.JPG",
    slideImage: [
      "/image/scalar/DSCF5753.JPG",
      "/image/scalar/DSCF57531.jpg",
      "/image/scalar/DSCF57533.jpg",
      "/image/scalar/DSCF57537_.jpg",
      "/image/scalar/Jy1001.jpg",
    ],
  },
  {
    id: 8,
    name: "N SHAPE TONGUE SCRAPPER",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor nisi. Non dolore ipsam consequuntur id repudiandae, quibusdam distinctio? Blanditiis, obcaecati animi? Similique exercitationem quo.",
    image: "/image/scrapper/zhujin1_.jpg",
    slideImage: [
      "/image/scrapper/zhujin1_.jpg",
      "/image/scrapper/zhujin3_.jpg",
      "/image/scrapper/zhujin4_.jpg",
      "/image/scrapper/zhujin5_.jpg",
      "/image/scrapper/zhujin6_.jpg",
      "/image/scrapper/zhuyin1.jpg",
      "/image/scrapper/zhuyin2.jpg",
      "/image/scrapper/zhuyin4.jpg",
      "/image/scrapper/zhuyin5.jpg",
    ],
  },
  {
    id: 9,
    name: "SPOON TONGUE SCRAPPER",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor nisi",
    image: "/image/spoontongue/1(2).jpg",
    slideImage: [
      "/image/spoontongue/1(2).jpg",
      "/image/spoontongue/3(4).jpg",
      "/image/spoontongue/5(4).jpg",
      "/image/spoontongue/detail page.jpg",
      "/image/spoontongue/6.jpg",
      "/image/spoontongue/7.jpg",
    ],
  },
  {
    id: 10,
    name: "SPOON TONGUE SCRAPPER",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium,.",
    image: "/image/tongueskrapper/112g2.jpg",
    slideImage: [
      "/image/tongueskrapper/112g2.jpg",
      "/image/tongueskrapper/112g3.jpg",
      "/image/tongueskrapper/112g5.jpg",
      "/image/tongueskrapper/112g6.jpg",
      "/image/tongueskrapper/112g7.jpg",
      "/image/tongueskrapper/112g8.jpg",
      "/image/tongueskrapper/112g9.jpg",
    ],
  },
  {
    id: 11,
    name: "ELECTRIC TOOTHBRUSH",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolo",
    image: "/image/toothbrush/fas10.jpg",
    slideImage: [
      "/image/toothbrush/fas10.jpg",
      "/image/toothbrush/35_.jpg",
      "/image/toothbrush/fas1.jpg",
      "/image/toothbrush/fas3.jpg",
      "/image/toothbrush/fas5.jpg",
      "/image/toothbrush/fas10.jpg",
      "/image/toothbrush/detail page.jpg",
      "/image/toothbrush/fas12.jpg",
      "/image/toothbrush/fas13.jpg",
      "/image/toothbrush/fas14.jpg",
      "/image/toothbrush/fas15.jpg",
      "/image/toothbrush/ys500.11_.jpg",
      "/image/toothbrush/ys500.18.jpg",
      "/image/toothbrush/ys500.20_.jpg",
    ],
  },
  {
    id: 12,
    name: "HOME ULTRASONIC STERILISING",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantium, odit impedit sequi iure at nostrum saepe amet officiis dolorem aut eveniet mollitia illo quibusdam laudantium atque sint tempore dolor nisi. Non dolore ipsam consequuntur id repudiandae, quibusdam distinctio? Blanditiis, obcaecati animi? Similique exercitatione",
    image: "/image/utrasonic/qx105.1.jpg",
    slideImage: [
      "/image/utrasonic/qx105.1.jpg",
      "/image/utrasonic/105.57_.jpg",
      "/image/utrasonic/452343jk.jpg",
      "/image/utrasonic/452343jk1.jpg",
      "/image/utrasonic/detail page.jpg",
      "/image/utrasonic/qx105.1(1.jpg",
      "/image/utrasonic/qx105.3.jpg",
      "/image/utrasonic/qx105.4.jpg",
      "/image/utrasonic/qx105.7.jpg",
      "/image/utrasonic/qx105.8.jpg",
      "/image/utrasonic/qx105.45.jpg",
    ],
  },
  {
    id: 13,
    name: "SUPER WATERFLOSSER",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, minima numquam. Minus sunt culpa, voluptas, fuga labore perspiciatis accusantiu",
    image: "/image/waterflow/2(2.png",
    slideImage: [
      "/image/waterflow/2(2.png",
      "/image/waterflow/4(2.png",
      "/image/waterflow/5(2.png",
      "/image/waterflow/6(2.png",
      "/image/waterflow/8(2.png",
      "/image/waterflow/zg11.jpg",
      "/image/waterflow/zg13.jpg",
    ],
  },
];
